name: mi_card
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Thêm ảnh cho ứng dụng. Đảm bảo ảnh của bạn nằm trong thư mục assets/images
  assets:
    - assets/images/avatar.jpg

  # Thêm font chữ Pacifico và Source Sans Pro vào ứng dụng.
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
